{% set name = "mzyzek-awk" %}
{% set version = "1.01" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: HEAD
  git_url: 'https://github.com/onetrueawk/awk'

build:
  script: "${RECIPE_DIR}/make.sh"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/onetrueawk/awk"
  summary: " mzyzek awk test"

